### ISSUE TITLE
Open All Unread not working in FF40

### ISSUE THREAD

**Issue by marchandmaximo** [coverprice/SAplusplus#1]
The button that will open all unread threads in new tabs opens tabs but the user cannot exit the tab or it hangs when trying to close it.  Started in Firefox 39.

**Comment by coverprice** [comment]
What version of GreaseMonkey are you running? I'm running GM3.3 and FF39.0.3 and I can't replicate the problem.

**Comment by marchandmaximo** [comment]
GM3.3 on FF40.  I recently switched to uBlock origin from ADP, I added the stylesheets in the filter list and it seems to be working now.

**Comment by scejrussell** [comment]
I'm seeing this problem now that I've upgraded to FF40. Disabling ABP and SALR didn't help. It looks like a GreaseMonkey issue that other people are seeing too: https://github.com/greasemonkey/greasemonkey/issues/2234

**Comment by marchandmaximo** [comment]
Changing browser.tabs.insertrelatedaftercurrent in about:config fixed it for me.  For some reason it did work for a while before this, so I hastily closed the issue.
